/**
 * starterSnippets.js - Problem-tailored starter templates and boilerplate code for AlgoLens.
 *
 * Provides unique, syntactically valid, compatible starter code snippets for every problem
 * in the AlgoLens problem bank across all supported languages (Java, Python, C++, C, JavaScript).
 */

export const DEFAULT_TEMPLATES = {
  java: `import java.util.*;

public class Solution {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        // Read input and write your solution here
    }
}
`,
  python: `import sys

def main():
    input_data = sys.stdin.read().split()
    if not input_data:
        return
    # Read input and write your solution here

if __name__ == "__main__":
    main()
`,
  cpp: `#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    // Read input and write your solution here
    return 0;
}
`,
  c: `#include <stdio.h>
#include <stdlib.h>

int main() {
    // Read input and write your solution here
    return 0;
}
`,
  javascript: `const fs = require('fs');

function main() {
    const input = fs.readFileSync(0, 'utf-8');
    // Read input and write your solution here
}

main();
`,
  mysql: `# Write your MySQL query statement below
SELECT 
    *
FROM 
    TableName;
`,
  sql: `-- Write your SQL query statement below
SELECT 
    *
FROM 
    TableName;
`,
};

export const PROBLEM_STARTER_SNIPPETS = {
  "Minimum Number of Pushes to Type Word I": {
    "python": "import sys\n\ndef minimum_pushes(word: str) -> int:\n    # TODO: Implement your solution here\n    return 0\n\ndef main():\n    lines = sys.stdin.read().split()\n    if not lines:\n        return\n    word = lines[0].strip()\n    result = minimum_pushes(word)\n    print(result)\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.Scanner;\n\npublic class Solution {\n    public static int minimumPushes(String word) {\n        // TODO: Implement your solution here\n        return 0;\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNext()) return;\n        String word = sc.next();\n        int result = minimumPushes(word);\n        System.out.println(result);\n    }\n}",
    "cpp": "#include <iostream>\n#include <string>\nusing namespace std;\n\nint minimumPushes(const string& word) {\n    // TODO: Implement your solution here\n    return 0;\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    string word;\n    if (!(cin >> word)) return 0;\n    int result = minimumPushes(word);\n    cout << result << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <string.h>\n\nint minimumPushes(const char* word) {\n    // TODO: Implement your solution here\n    return 0;\n}\n\nint main() {\n    char word[100];\n    if (scanf(\"%99s\", word) != 1) return 0;\n    int result = minimumPushes(word);\n    printf(\"%d\\n\", result);\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction minimumPushes(word) {\n    // TODO: Implement your solution here\n    return 0;\n}\n\nfunction main() {\n    const input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/);\n    if (!input || input.length === 0 || !input[0]) return;\n    const word = input[0];\n    const result = minimumPushes(word);\n    console.log(result);\n}\n\nmain();"
  },
  "Two Sum": {
    "python": "import sys\n\ndef two_sum(nums: list[int], target: int) -> list[int]:\n    # TODO: Implement your solution here\n    return []\n\ndef main():\n    input_data = sys.stdin.read().split()\n    if not input_data:\n        return\n    n = int(input_data[0])\n    nums = [int(x) for x in input_data[1:n+1]]\n    target = int(input_data[n+1])\n\n    result = two_sum(nums, target)\n    if result:\n        res = sorted(result)\n        print(f\"{res[0]} {res[1]}\")\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.*;\n\npublic class Solution {\n    public static int[] twoSum(int[] nums, int target) {\n        // TODO: Implement your solution here\n        return new int[]{};\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int n = sc.nextInt();\n        int[] nums = new int[n];\n        for (int i = 0; i < n; i++) nums[i] = sc.nextInt();\n        int target = sc.nextInt();\n\n        int[] result = twoSum(nums, target);\n        if (result != null && result.length >= 2) {\n            int a = Math.min(result[0], result[1]);\n            int b = Math.max(result[0], result[1]);\n            System.out.println(a + \" \" + b);\n        }\n    }\n}",
    "cpp": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nvector<int> twoSum(vector<int>& nums, int target) {\n    // TODO: Implement your solution here\n    return {};\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    int n;\n    if (!(cin >> n)) return 0;\n    vector<int> nums(n);\n    for (int i = 0; i < n; i++) cin >> nums[i];\n    int target;\n    cin >> target;\n\n    vector<int> result = twoSum(nums, target);\n    if (result.size() >= 2) {\n        if (result[0] > result[1]) swap(result[0], result[1]);\n        cout << result[0] << \" \" << result[1] << \"\\n\";\n    }\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nvoid twoSum(int* nums, int n, int target, int* idx1, int* idx2) {\n    // TODO: Implement your solution here\n    *idx1 = 0;\n    *idx2 = 0;\n}\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1) return 0;\n    int* nums = (int*)malloc(n * sizeof(int));\n    for (int i = 0; i < n; i++) scanf(\"%d\", &nums[i]);\n    int target;\n    scanf(\"%d\", &target);\n\n    int idx1 = 0, idx2 = 0;\n    twoSum(nums, n, target, &idx1, &idx2);\n    if (idx1 > idx2) { int t = idx1; idx1 = idx2; idx2 = t; }\n    printf(\"%d %d\\n\", idx1, idx2);\n    free(nums);\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction twoSum(nums, target) {\n    // TODO: Implement your solution here\n    return [];\n}\n\nfunction main() {\n    const input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\n    if (!input || input.length === 0 || isNaN(input[0])) return;\n    const n = input[0];\n    const nums = input.slice(1, n + 1);\n    const target = input[n + 1];\n\n    const result = twoSum(nums, target);\n    if (result && result.length >= 2) {\n        const sorted = [...result].sort((a, b) => a - b);\n        console.log(`${sorted[0]} ${sorted[1]}`);\n    }\n}\n\nmain();"
  },
  "Add Two Numbers": {
    "python": "import sys\n\ndef add_two_numbers(l1: list[int], l2: list[int]) -> list[int]:\n    # TODO: Implement your solution here\n    # Digits are stored in reverse order\n    return []\n\ndef main():\n    lines = sys.stdin.read().strip().split('\\n')\n    if not lines or not lines[0].strip():\n        return\n    l1 = [int(x) for x in lines[0].split()]\n    l2 = [int(x) for x in lines[1].split()] if len(lines) > 1 and lines[1].strip() else []\n\n    result = add_two_numbers(l1, l2)\n    print(\" \".join(map(str, result)))\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.*;\n\npublic class Solution {\n    public static List<Integer> addTwoNumbers(List<Integer> l1, List<Integer> l2) {\n        // TODO: Implement your solution here\n        return new ArrayList<>();\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextLine()) return;\n        String line1 = sc.nextLine().trim();\n        String line2 = sc.hasNextLine() ? sc.nextLine().trim() : \"\";\n\n        List<Integer> l1 = new ArrayList<>();\n        if (!line1.isEmpty()) {\n            for (String s : line1.split(\"\\\\s+\")) l1.add(Integer.parseInt(s));\n        }\n        List<Integer> l2 = new ArrayList<>();\n        if (!line2.isEmpty()) {\n            for (String s : line2.split(\"\\\\s+\")) l2.add(Integer.parseInt(s));\n        }\n\n        List<Integer> result = addTwoNumbers(l1, l2);\n        StringBuilder sb = new StringBuilder();\n        for (int i = 0; i < result.size(); i++) {\n            if (i > 0) sb.append(\" \");\n            sb.append(result.get(i));\n        }\n        System.out.println(sb.toString());\n    }\n}",
    "cpp": "#include <iostream>\n#include <vector>\n#include <string>\n#include <sstream>\nusing namespace std;\n\nvector<int> addTwoNumbers(const vector<int>& l1, const vector<int>& l2) {\n    // TODO: Implement your solution here\n    return {};\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    string line1, line2;\n    if (!getline(cin, line1)) return 0;\n    getline(cin, line2);\n\n    vector<int> l1, l2;\n    stringstream ss1(line1), ss2(line2);\n    int val;\n    while (ss1 >> val) l1.push_back(val);\n    while (ss2 >> val) l2.push_back(val);\n\n    vector<int> result = addTwoNumbers(l1, l2);\n    for (size_t i = 0; i < result.size(); i++) {\n        cout << result[i] << (i + 1 == result.size() ? \"\" : \" \");\n    }\n    cout << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n\nint main() {\n    // TODO: Implement your solution here\n    char line1[1000], line2[1000];\n    if (!fgets(line1, sizeof(line1), stdin)) return 0;\n    fgets(line2, sizeof(line2), stdin);\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction addTwoNumbers(l1, l2) {\n    // TODO: Implement your solution here\n    return [];\n}\n\nfunction main() {\n    const lines = fs.readFileSync(0, 'utf-8').trim().split('\\n');\n    if (!lines || lines.length === 0 || !lines[0].trim()) return;\n    const l1 = lines[0].trim().split(/\\s+/).map(Number);\n    const l2 = lines[1] ? lines[1].trim().split(/\\s+/).map(Number) : [];\n\n    const result = addTwoNumbers(l1, l2);\n    console.log(result.join(' '));\n}\n\nmain();"
  },
  "Longest Substring Without Repeating Characters": {
    "python": "import sys\n\ndef length_of_longest_substring(s: str) -> int:\n    # TODO: Implement your solution here\n    return 0\n\ndef main():\n    s = sys.stdin.read().rstrip('\\r\\n')\n    result = length_of_longest_substring(s)\n    print(result)\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.Scanner;\n\npublic class Solution {\n    public static int lengthOfLongestSubstring(String s) {\n        // TODO: Implement your solution here\n        return 0;\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.hasNextLine() ? sc.nextLine() : \"\";\n        int result = lengthOfLongestSubstring(s);\n        System.out.println(result);\n    }\n}",
    "cpp": "#include <iostream>\n#include <string>\nusing namespace std;\n\nint lengthOfLongestSubstring(const string& s) {\n    // TODO: Implement your solution here\n    return 0;\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    string s;\n    getline(cin, s);\n    int result = lengthOfLongestSubstring(s);\n    cout << result << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <string.h>\n\nint lengthOfLongestSubstring(const char* s) {\n    // TODO: Implement your solution here\n    return 0;\n}\n\nint main() {\n    char s[100005];\n    if (!fgets(s, sizeof(s), stdin)) return 0;\n    s[strcspn(s, \"\\r\\n\")] = '\\0';\n    int result = lengthOfLongestSubstring(s);\n    printf(\"%d\\n\", result);\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction lengthOfLongestSubstring(s) {\n    // TODO: Implement your solution here\n    return 0;\n}\n\nfunction main() {\n    const s = fs.readFileSync(0, 'utf-8').replace(/\\r?\\n$/, '');\n    const result = lengthOfLongestSubstring(s);\n    console.log(result);\n}\n\nmain();"
  },
  "Median of Two Sorted Arrays": {
    "python": "import sys\n\ndef find_median_sorted_arrays(nums1: list[int], nums2: list[int]) -> float:\n    # TODO: Implement your solution here\n    return 0.0\n\ndef main():\n    lines = sys.stdin.read().strip().split('\\n')\n    if not lines:\n        return\n    nums1 = [int(x) for x in lines[0].split()] if lines[0].strip() else []\n    nums2 = [int(x) for x in lines[1].split()] if len(lines) > 1 and lines[1].strip() else []\n\n    result = find_median_sorted_arrays(nums1, nums2)\n    print(f\"{result:.1f}\" if result == int(result) else f\"{result}\")\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.*;\n\npublic class Solution {\n    public static double findMedianSortedArrays(int[] nums1, int[] nums2) {\n        // TODO: Implement your solution here\n        return 0.0;\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String line1 = sc.hasNextLine() ? sc.nextLine().trim() : \"\";\n        String line2 = sc.hasNextLine() ? sc.nextLine().trim() : \"\";\n\n        int[] nums1 = line1.isEmpty() ? new int[0] : Arrays.stream(line1.split(\"\\\\s+\")).mapToInt(Integer::parseInt).toArray();\n        int[] nums2 = line2.isEmpty() ? new int[0] : Arrays.stream(line2.split(\"\\\\s+\")).mapToInt(Integer::parseInt).toArray();\n\n        double result = findMedianSortedArrays(nums1, nums2);\n        System.out.println(result);\n    }\n}",
    "cpp": "#include <iostream>\n#include <vector>\n#include <string>\n#include <sstream>\n#include <iomanip>\nusing namespace std;\n\ndouble findMedianSortedArrays(vector<int>& nums1, vector<int>& nums2) {\n    // TODO: Implement your solution here\n    return 0.0;\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    string line1, line2;\n    getline(cin, line1);\n    getline(cin, line2);\n\n    vector<int> nums1, nums2;\n    stringstream ss1(line1), ss2(line2);\n    int val;\n    while (ss1 >> val) nums1.push_back(val);\n    while (ss2 >> val) nums2.push_back(val);\n\n    double result = findMedianSortedArrays(nums1, nums2);\n    cout << fixed << setprecision(1) << result << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    // TODO: Implement median of two sorted arrays\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction findMedianSortedArrays(nums1, nums2) {\n    // TODO: Implement your solution here\n    return 0.0;\n}\n\nfunction main() {\n    const lines = fs.readFileSync(0, 'utf-8').trim().split('\\n');\n    if (!lines) return;\n    const nums1 = lines[0] && lines[0].trim() ? lines[0].trim().split(/\\s+/).map(Number) : [];\n    const nums2 = lines[1] && lines[1].trim() ? lines[1].trim().split(/\\s+/).map(Number) : [];\n\n    const result = findMedianSortedArrays(nums1, nums2);\n    console.log(result.toFixed(1));\n}\n\nmain();"
  },
  "Longest Palindromic Substring": {
    "python": "import sys\n\ndef longest_palindrome(s: str) -> str:\n    # TODO: Implement your solution here\n    return \"\"\n\ndef main():\n    s = sys.stdin.read().strip()\n    if not s:\n        return\n    result = longest_palindrome(s)\n    print(result)\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.Scanner;\n\npublic class Solution {\n    public static String longestPalindrome(String s) {\n        // TODO: Implement your solution here\n        return \"\";\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNext()) return;\n        String s = sc.next();\n        String result = longestPalindrome(s);\n        System.out.println(result);\n    }\n}",
    "cpp": "#include <iostream>\n#include <string>\nusing namespace std;\n\nstring longestPalindrome(const string& s) {\n    // TODO: Implement your solution here\n    return \"\";\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    string s;\n    if (!(cin >> s)) return 0;\n    string result = longestPalindrome(s);\n    cout << result << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <string.h>\n\nvoid longestPalindrome(const char* s, char* out) {\n    // TODO: Implement your solution here\n    out[0] = '\\0';\n}\n\nint main() {\n    char s[10005], out[10005];\n    if (scanf(\"%10000s\", s) != 1) return 0;\n    longestPalindrome(s, out);\n    printf(\"%s\\n\", out);\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction longestPalindrome(s) {\n    // TODO: Implement your solution here\n    return \"\";\n}\n\nfunction main() {\n    const s = fs.readFileSync(0, 'utf-8').trim();\n    if (!s) return;\n    const result = longestPalindrome(s);\n    console.log(result);\n}\n\nmain();"
  },
  "Zigzag Conversion": {
    "python": "import sys\n\ndef convert(s: str, num_rows: int) -> str:\n    # TODO: Implement your solution here\n    return s\n\ndef main():\n    lines = sys.stdin.read().strip().split('\\n')\n    if not lines:\n        return\n    s = lines[0].strip()\n    num_rows = int(lines[1].strip()) if len(lines) > 1 else 1\n    result = convert(s, num_rows)\n    print(result)\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.Scanner;\n\npublic class Solution {\n    public static String convert(String s, int numRows) {\n        // TODO: Implement your solution here\n        return s;\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNext()) return;\n        String s = sc.next();\n        int numRows = sc.hasNextInt() ? sc.nextInt() : 1;\n        String result = convert(s, numRows);\n        System.out.println(result);\n    }\n}",
    "cpp": "#include <iostream>\n#include <string>\nusing namespace std;\n\nstring convert(const string& s, int numRows) {\n    // TODO: Implement your solution here\n    return s;\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    string s;\n    int numRows;\n    if (!(cin >> s >> numRows)) return 0;\n    string result = convert(s, numRows);\n    cout << result << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <string.h>\n\nint main() {\n    // TODO: Implement zigzag conversion\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction convert(s, numRows) {\n    // TODO: Implement your solution here\n    return s;\n}\n\nfunction main() {\n    const input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/);\n    if (!input || input.length < 2) return;\n    const s = input[0];\n    const numRows = parseInt(input[1], 10);\n    const result = convert(s, numRows);\n    console.log(result);\n}\n\nmain();"
  },
  "Reverse Integer": {
    "python": "import sys\n\ndef reverse(x: int) -> int:\n    # TODO: Implement your solution here (handle 32-bit signed overflow)\n    return 0\n\ndef main():\n    s = sys.stdin.read().strip()\n    if not s:\n        return\n    x = int(s)\n    result = reverse(x)\n    print(result)\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.Scanner;\n\npublic class Solution {\n    public static int reverse(int x) {\n        // TODO: Implement your solution here (handle 32-bit signed overflow)\n        return 0;\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int x = sc.nextInt();\n        int result = reverse(x);\n        System.out.println(result);\n    }\n}",
    "cpp": "#include <iostream>\nusing namespace std;\n\nint reverse(int x) {\n    // TODO: Implement your solution here (handle 32-bit signed overflow)\n    return 0;\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    int x;\n    if (!(cin >> x)) return 0;\n    int result = reverse(x);\n    cout << result << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n\nint reverse(int x) {\n    // TODO: Implement your solution here (handle 32-bit signed overflow)\n    return 0;\n}\n\nint main() {\n    int x;\n    if (scanf(\"%d\", &x) != 1) return 0;\n    int result = reverse(x);\n    printf(\"%d\\n\", result);\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction reverse(x) {\n    // TODO: Implement your solution here (handle 32-bit signed overflow)\n    return 0;\n}\n\nfunction main() {\n    const input = fs.readFileSync(0, 'utf-8').trim();\n    if (!input) return;\n    const x = parseInt(input, 10);\n    const result = reverse(x);\n    console.log(result);\n}\n\nmain();"
  },
  "String to Integer (atoi)": {
    "python": "import sys\n\ndef my_atoi(s: str) -> int:\n    # TODO: Implement your solution here (clamp to [-2^31, 2^31 - 1])\n    return 0\n\ndef main():\n    s = sys.stdin.read().rstrip('\\r\\n')\n    result = my_atoi(s)\n    print(result)\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.Scanner;\n\npublic class Solution {\n    public static int myAtoi(String s) {\n        // TODO: Implement your solution here (clamp to [-2^31, 2^31 - 1])\n        return 0;\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.hasNextLine() ? sc.nextLine() : \"\";\n        int result = myAtoi(s);\n        System.out.println(result);\n    }\n}",
    "cpp": "#include <iostream>\n#include <string>\nusing namespace std;\n\nint myAtoi(string s) {\n    // TODO: Implement your solution here (clamp to [-2^31, 2^31 - 1])\n    return 0;\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    string s;\n    getline(cin, s);\n    int result = myAtoi(s);\n    cout << result << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <string.h>\n\nint myAtoi(const char* s) {\n    // TODO: Implement your solution here\n    return 0;\n}\n\nint main() {\n    char s[10000];\n    if (!fgets(s, sizeof(s), stdin)) return 0;\n    s[strcspn(s, \"\\r\\n\")] = '\\0';\n    int result = myAtoi(s);\n    printf(\"%d\\n\", result);\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction myAtoi(s) {\n    // TODO: Implement your solution here\n    return 0;\n}\n\nfunction main() {\n    const s = fs.readFileSync(0, 'utf-8').replace(/\\r?\\n$/, '');\n    const result = myAtoi(s);\n    console.log(result);\n}\n\nmain();"
  },
  "Palindrome Number": {
    "python": "import sys\n\ndef is_palindrome(x: int) -> bool:\n    # TODO: Implement your solution here\n    return False\n\ndef main():\n    s = sys.stdin.read().strip()\n    if not s:\n        return\n    x = int(s)\n    result = is_palindrome(x)\n    print(\"true\" if result else \"false\")\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.Scanner;\n\npublic class Solution {\n    public static boolean isPalindrome(int x) {\n        // TODO: Implement your solution here\n        return false;\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int x = sc.nextInt();\n        boolean result = isPalindrome(x);\n        System.out.println(result ? \"true\" : \"false\");\n    }\n}",
    "cpp": "#include <iostream>\nusing namespace std;\n\nbool isPalindrome(int x) {\n    // TODO: Implement your solution here\n    return false;\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    int x;\n    if (!(cin >> x)) return 0;\n    bool result = isPalindrome(x);\n    cout << (result ? \"true\" : \"false\") << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <stdbool.h>\n\nbool isPalindrome(int x) {\n    // TODO: Implement your solution here\n    return false;\n}\n\nint main() {\n    int x;\n    if (scanf(\"%d\", &x) != 1) return 0;\n    bool result = isPalindrome(x);\n    printf(\"%s\\n\", result ? \"true\" : \"false\");\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction isPalindrome(x) {\n    // TODO: Implement your solution here\n    return false;\n}\n\nfunction main() {\n    const input = fs.readFileSync(0, 'utf-8').trim();\n    if (!input) return;\n    const x = parseInt(input, 10);\n    const result = isPalindrome(x);\n    console.log(result ? \"true\" : \"false\");\n}\n\nmain();"
  },
  "Regular Expression Matching": {
    "python": "import sys\n\ndef is_match(s: str, p: str) -> bool:\n    # TODO: Implement your solution here (supports '.' and '*')\n    return False\n\ndef main():\n    lines = sys.stdin.read().strip().split('\\n')\n    if not lines:\n        return\n    s = lines[0].strip() if lines[0].strip() else \"\"\n    p = lines[1].strip() if len(lines) > 1 and lines[1].strip() else \"\"\n\n    result = is_match(s, p)\n    print(\"true\" if result else \"false\")\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.Scanner;\n\npublic class Solution {\n    public static boolean isMatch(String s, String p) {\n        // TODO: Implement your solution here (supports '.' and '*')\n        return false;\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.hasNextLine() ? sc.nextLine().trim() : \"\";\n        String p = sc.hasNextLine() ? sc.nextLine().trim() : \"\";\n\n        boolean result = isMatch(s, p);\n        System.out.println(result ? \"true\" : \"false\");\n    }\n}",
    "cpp": "#include <iostream>\n#include <string>\nusing namespace std;\n\nbool isMatch(const string& s, const string& p) {\n    // TODO: Implement your solution here (supports '.' and '*')\n    return false;\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    string s, p;\n    getline(cin, s);\n    getline(cin, p);\n\n    bool result = isMatch(s, p);\n    cout << (result ? \"true\" : \"false\") << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <stdbool.h>\n\nint main() {\n    // TODO: Implement regular expression matching\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction isMatch(s, p) {\n    // TODO: Implement your solution here (supports '.' and '*')\n    return false;\n}\n\nfunction main() {\n    const lines = fs.readFileSync(0, 'utf-8').trim().split('\\n');\n    if (!lines) return;\n    const s = lines[0] ? lines[0].trim() : \"\";\n    const p = lines[1] ? lines[1].trim() : \"\";\n\n    const result = isMatch(s, p);\n    console.log(result ? \"true\" : \"false\");\n}\n\nmain();"
  },
  "Container With Most Water": {
    "python": "import sys\n\ndef max_area(height: list[int]) -> int:\n    # TODO: Implement your solution here\n    return 0\n\ndef main():\n    input_data = sys.stdin.read().split()\n    if not input_data:\n        return\n    n = int(input_data[0])\n    height = [int(x) for x in input_data[1:n+1]]\n\n    result = max_area(height)\n    print(result)\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.Scanner;\n\npublic class Solution {\n    public static int maxArea(int[] height) {\n        // TODO: Implement your solution here\n        return 0;\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int n = sc.nextInt();\n        int[] height = new int[n];\n        for (int i = 0; i < n; i++) height[i] = sc.nextInt();\n\n        int result = maxArea(height);\n        System.out.println(result);\n    }\n}",
    "cpp": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint maxArea(vector<int>& height) {\n    // TODO: Implement your solution here\n    return 0;\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    int n;\n    if (!(cin >> n)) return 0;\n    vector<int> height(n);\n    for (int i = 0; i < n; i++) cin >> height[i];\n\n    int result = maxArea(height);\n    cout << result << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint maxArea(int* height, int n) {\n    // TODO: Implement your solution here\n    return 0;\n}\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1) return 0;\n    int* height = (int*)malloc(n * sizeof(int));\n    for (int i = 0; i < n; i++) scanf(\"%d\", &height[i]);\n\n    int result = maxArea(height, n);\n    printf(\"%d\\n\", result);\n    free(height);\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction maxArea(height) {\n    // TODO: Implement your solution here\n    return 0;\n}\n\nfunction main() {\n    const input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\n    if (!input || input.length === 0 || isNaN(input[0])) return;\n    const n = input[0];\n    const height = input.slice(1, n + 1);\n\n    const result = maxArea(height);\n    console.log(result);\n}\n\nmain();"
  },
  "Integer to Roman": {
    "python": "import sys\n\ndef int_to_roman(num: int) -> str:\n    # TODO: Implement your solution here\n    return \"\"\n\ndef main():\n    s = sys.stdin.read().strip()\n    if not s:\n        return\n    num = int(s)\n    result = int_to_roman(num)\n    print(result)\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.Scanner;\n\npublic class Solution {\n    public static String intToRoman(int num) {\n        // TODO: Implement your solution here\n        return \"\";\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int num = sc.nextInt();\n        String result = intToRoman(num);\n        System.out.println(result);\n    }\n}",
    "cpp": "#include <iostream>\n#include <string>\nusing namespace std;\n\nstring intToRoman(int num) {\n    // TODO: Implement your solution here\n    return \"\";\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    int num;\n    if (!(cin >> num)) return 0;\n    string result = intToRoman(num);\n    cout << result << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n\nint main() {\n    // TODO: Implement integer to roman\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction intToRoman(num) {\n    // TODO: Implement your solution here\n    return \"\";\n}\n\nfunction main() {\n    const input = fs.readFileSync(0, 'utf-8').trim();\n    if (!input) return;\n    const num = parseInt(input, 10);\n    const result = intToRoman(num);\n    console.log(result);\n}\n\nmain();"
  },
  "Roman to Integer": {
    "python": "import sys\n\ndef roman_to_int(s: str) -> int:\n    # TODO: Implement your solution here\n    return 0\n\ndef main():\n    s = sys.stdin.read().strip()\n    if not s:\n        return\n    result = roman_to_int(s)\n    print(result)\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.Scanner;\n\npublic class Solution {\n    public static int romanToInt(String s) {\n        // TODO: Implement your solution here\n        return 0;\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNext()) return;\n        String s = sc.next();\n        int result = romanToInt(s);\n        System.out.println(result);\n    }\n}",
    "cpp": "#include <iostream>\n#include <string>\nusing namespace std;\n\nint romanToInt(const string& s) {\n    // TODO: Implement your solution here\n    return 0;\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    string s;\n    if (!(cin >> s)) return 0;\n    int result = romanToInt(s);\n    cout << result << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <string.h>\n\nint romanToInt(const char* s) {\n    // TODO: Implement your solution here\n    return 0;\n}\n\nint main() {\n    char s[100];\n    if (scanf(\"%99s\", s) != 1) return 0;\n    int result = romanToInt(s);\n    printf(\"%d\\n\", result);\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction romanToInt(s) {\n    // TODO: Implement your solution here\n    return 0;\n}\n\nfunction main() {\n    const s = fs.readFileSync(0, 'utf-8').trim();\n    if (!s) return;\n    const result = romanToInt(s);\n    console.log(result);\n}\n\nmain();"
  },
  "3Sum": {
    "python": "import sys\n\ndef three_sum(nums: list[int]) -> list[list[int]]:\n    # TODO: Implement your solution here\n    return []\n\ndef main():\n    input_data = sys.stdin.read().split()\n    if not input_data:\n        return\n    n = int(input_data[0])\n    nums = [int(x) for x in input_data[1:n+1]]\n\n    result = three_sum(nums)\n    for triplet in sorted(result):\n        print(f\"{triplet[0]} {triplet[1]} {triplet[2]}\")\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.*;\n\npublic class Solution {\n    public static List<List<Integer>> threeSum(int[] nums) {\n        // TODO: Implement your solution here\n        return new ArrayList<>();\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int n = sc.nextInt();\n        int[] nums = new int[n];\n        for (int i = 0; i < n; i++) nums[i] = sc.nextInt();\n\n        List<List<Integer>> result = threeSum(nums);\n        for (List<Integer> triplet : result) {\n            System.out.println(triplet.get(0) + \" \" + triplet.get(1) + \" \" + triplet.get(2));\n        }\n    }\n}",
    "cpp": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nvector<vector<int>> threeSum(vector<int>& nums) {\n    // TODO: Implement your solution here\n    return {};\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    int n;\n    if (!(cin >> n)) return 0;\n    vector<int> nums(n);\n    for (int i = 0; i < n; i++) cin >> nums[i];\n\n    vector<vector<int>> result = threeSum(nums);\n    for (const auto& triplet : result) {\n        cout << triplet[0] << \" \" << triplet[1] << \" \" << triplet[2] << \"\\n\";\n    }\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    // TODO: Implement 3Sum\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction threeSum(nums) {\n    // TODO: Implement your solution here\n    return [];\n}\n\nfunction main() {\n    const input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\n    if (!input || input.length === 0 || isNaN(input[0])) return;\n    const n = input[0];\n    const nums = input.slice(1, n + 1);\n\n    const result = threeSum(nums);\n    for (const triplet of result) {\n        console.log(triplet.join(' '));\n    }\n}\n\nmain();"
  },
  "3Sum Closest": {
    "python": "import sys\n\ndef three_sum_closest(nums: list[int], target: int) -> int:\n    # TODO: Implement your solution here\n    return 0\n\ndef main():\n    input_data = sys.stdin.read().split()\n    if not input_data:\n        return\n    n = int(input_data[0])\n    nums = [int(x) for x in input_data[1:n+1]]\n    target = int(input_data[n+1])\n\n    result = three_sum_closest(nums, target)\n    print(result)\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.*;\n\npublic class Solution {\n    public static int threeSumClosest(int[] nums, int target) {\n        // TODO: Implement your solution here\n        return 0;\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int n = sc.nextInt();\n        int[] nums = new int[n];\n        for (int i = 0; i < n; i++) nums[i] = sc.nextInt();\n        int target = sc.nextInt();\n\n        int result = threeSumClosest(nums, target);\n        System.out.println(result);\n    }\n}",
    "cpp": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint threeSumClosest(vector<int>& nums, int target) {\n    // TODO: Implement your solution here\n    return 0;\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    int n;\n    if (!(cin >> n)) return 0;\n    vector<int> nums(n);\n    for (int i = 0; i < n; i++) cin >> nums[i];\n    int target;\n    cin >> target;\n\n    int result = threeSumClosest(nums, target);\n    cout << result << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    // TODO: Implement 3Sum Closest\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction threeSumClosest(nums, target) {\n    // TODO: Implement your solution here\n    return 0;\n}\n\nfunction main() {\n    const input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\n    if (!input || input.length === 0 || isNaN(input[0])) return;\n    const n = input[0];\n    const nums = input.slice(1, n + 1);\n    const target = input[n + 1];\n\n    const result = threeSumClosest(nums, target);\n    console.log(result);\n}\n\nmain();"
  },
  "Valid Parentheses": {
    "python": "import sys\n\ndef is_valid(s: str) -> bool:\n    # TODO: Implement your solution here\n    return False\n\ndef main():\n    s = sys.stdin.read().strip()\n    result = is_valid(s)\n    print(\"true\" if result else \"false\")\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.*;\n\npublic class Solution {\n    public static boolean isValid(String s) {\n        // TODO: Implement your solution here\n        return false;\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.hasNext() ? sc.next() : \"\";\n        boolean result = isValid(s);\n        System.out.println(result ? \"true\" : \"false\");\n    }\n}",
    "cpp": "#include <iostream>\n#include <string>\n#include <stack>\nusing namespace std;\n\nbool isValid(const string& s) {\n    // TODO: Implement your solution here\n    return false;\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    string s;\n    if (!(cin >> s)) return 0;\n    bool result = isValid(s);\n    cout << (result ? \"true\" : \"false\") << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <stdbool.h>\n\nbool isValid(const char* s) {\n    // TODO: Implement your solution here\n    return false;\n}\n\nint main() {\n    char s[10005];\n    if (scanf(\"%10000s\", s) != 1) return 0;\n    bool result = isValid(s);\n    printf(\"%s\\n\", result ? \"true\" : \"false\");\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction isValid(s) {\n    // TODO: Implement your solution here\n    return false;\n}\n\nfunction main() {\n    const s = fs.readFileSync(0, 'utf-8').trim();\n    const result = isValid(s);\n    console.log(result ? \"true\" : \"false\");\n}\n\nmain();"
  },
  "Merge Two Sorted Lists": {
    "python": "import sys\n\ndef merge_two_lists(l1: list[int], l2: list[int]) -> list[int]:\n    # TODO: Implement your solution here\n    return []\n\ndef main():\n    lines = sys.stdin.read().strip().split('\\n')\n    if not lines:\n        return\n    l1 = [int(x) for x in lines[0].split()] if lines[0].strip() else []\n    l2 = [int(x) for x in lines[1].split()] if len(lines) > 1 and lines[1].strip() else []\n\n    result = merge_two_lists(l1, l2)\n    print(\" \".join(map(str, result)))\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.*;\n\npublic class Solution {\n    public static List<Integer> mergeTwoLists(List<Integer> l1, List<Integer> l2) {\n        // TODO: Implement your solution here\n        return new ArrayList<>();\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String line1 = sc.hasNextLine() ? sc.nextLine().trim() : \"\";\n        String line2 = sc.hasNextLine() ? sc.nextLine().trim() : \"\";\n\n        List<Integer> l1 = new ArrayList<>();\n        if (!line1.isEmpty()) {\n            for (String s : line1.split(\"\\\\s+\")) l1.add(Integer.parseInt(s));\n        }\n        List<Integer> l2 = new ArrayList<>();\n        if (!line2.isEmpty()) {\n            for (String s : line2.split(\"\\\\s+\")) l2.add(Integer.parseInt(s));\n        }\n\n        List<Integer> result = mergeTwoLists(l1, l2);\n        StringBuilder sb = new StringBuilder();\n        for (int i = 0; i < result.size(); i++) {\n            if (i > 0) sb.append(\" \");\n            sb.append(result.get(i));\n        }\n        System.out.println(sb.toString());\n    }\n}",
    "cpp": "#include <iostream>\n#include <vector>\n#include <string>\n#include <sstream>\nusing namespace std;\n\nvector<int> mergeTwoLists(const vector<int>& l1, const vector<int>& l2) {\n    // TODO: Implement your solution here\n    return {};\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    string line1, line2;\n    getline(cin, line1);\n    getline(cin, line2);\n\n    vector<int> l1, l2;\n    stringstream ss1(line1), ss2(line2);\n    int val;\n    while (ss1 >> val) l1.push_back(val);\n    while (ss2 >> val) l2.push_back(val);\n\n    vector<int> result = mergeTwoLists(l1, l2);\n    for (size_t i = 0; i < result.size(); i++) {\n        cout << result[i] << (i + 1 == result.size() ? \"\" : \" \");\n    }\n    cout << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    // TODO: Implement merge two sorted lists\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction mergeTwoLists(l1, l2) {\n    // TODO: Implement your solution here\n    return [];\n}\n\nfunction main() {\n    const lines = fs.readFileSync(0, 'utf-8').trim().split('\\n');\n    if (!lines) return;\n    const l1 = lines[0] && lines[0].trim() ? lines[0].trim().split(/\\s+/).map(Number) : [];\n    const l2 = lines[1] && lines[1].trim() ? lines[1].trim().split(/\\s+/).map(Number) : [];\n\n    const result = mergeTwoLists(l1, l2);\n    console.log(result.join(' '));\n}\n\nmain();"
  },
  "Best Time to Buy and Sell Stock": {
    "python": "import sys\n\ndef max_profit(prices: list[int]) -> int:\n    # TODO: Implement your solution here\n    return 0\n\ndef main():\n    input_data = sys.stdin.read().split()\n    if not input_data:\n        return\n    n = int(input_data[0])\n    prices = [int(x) for x in input_data[1:n+1]]\n\n    result = max_profit(prices)\n    print(result)\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.Scanner;\n\npublic class Solution {\n    public static int maxProfit(int[] prices) {\n        // TODO: Implement your solution here\n        return 0;\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int n = sc.nextInt();\n        int[] prices = new int[n];\n        for (int i = 0; i < n; i++) prices[i] = sc.nextInt();\n\n        int result = maxProfit(prices);\n        System.out.println(result);\n    }\n}",
    "cpp": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint maxProfit(vector<int>& prices) {\n    // TODO: Implement your solution here\n    return 0;\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    int n;\n    if (!(cin >> n)) return 0;\n    vector<int> prices(n);\n    for (int i = 0; i < n; i++) cin >> prices[i];\n\n    int result = maxProfit(prices);\n    cout << result << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint maxProfit(int* prices, int n) {\n    // TODO: Implement your solution here\n    return 0;\n}\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1) return 0;\n    int* prices = (int*)malloc(n * sizeof(int));\n    for (int i = 0; i < n; i++) scanf(\"%d\", &prices[i]);\n\n    int result = maxProfit(prices, n);\n    printf(\"%d\\n\", result);\n    free(prices);\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction maxProfit(prices) {\n    // TODO: Implement your solution here\n    return 0;\n}\n\nfunction main() {\n    const input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\n    if (!input || input.length === 0 || isNaN(input[0])) return;\n    const n = input[0];\n    const prices = input.slice(1, n + 1);\n\n    const result = maxProfit(prices);\n    console.log(result);\n}\n\nmain();"
  },
  "Valid Palindrome": {
    "python": "import sys\n\ndef is_palindrome(s: str) -> bool:\n    # TODO: Implement your solution here (ignoring non-alphanumeric and case)\n    return False\n\ndef main():\n    s = sys.stdin.read().strip()\n    result = is_palindrome(s)\n    print(\"true\" if result else \"false\")\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.Scanner;\n\npublic class Solution {\n    public static boolean isPalindrome(String s) {\n        // TODO: Implement your solution here (ignoring non-alphanumeric and case)\n        return false;\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.hasNextLine() ? sc.nextLine() : \"\";\n        boolean result = isPalindrome(s);\n        System.out.println(result ? \"true\" : \"false\");\n    }\n}",
    "cpp": "#include <iostream>\n#include <string>\n#include <cctype>\nusing namespace std;\n\nbool isPalindrome(const string& s) {\n    // TODO: Implement your solution here (ignoring non-alphanumeric and case)\n    return false;\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    string s;\n    getline(cin, s);\n    bool result = isPalindrome(s);\n    cout << (result ? \"true\" : \"false\") << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <stdbool.h>\n#include <string.h>\n\nbool isPalindrome(const char* s) {\n    // TODO: Implement your solution here\n    return false;\n}\n\nint main() {\n    char s[100005];\n    if (!fgets(s, sizeof(s), stdin)) return 0;\n    bool result = isPalindrome(s);\n    printf(\"%s\\n\", result ? \"true\" : \"false\");\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction isPalindrome(s) {\n    // TODO: Implement your solution here (ignoring non-alphanumeric and case)\n    return false;\n}\n\nfunction main() {\n    const s = fs.readFileSync(0, 'utf-8').trim();\n    const result = isPalindrome(s);\n    console.log(result ? \"true\" : \"false\");\n}\n\nmain();"
  },
  "Maximum Subarray": {
    "python": "import sys\n\ndef max_sub_array(nums: list[int]) -> int:\n    # TODO: Implement your solution here (Kadane's algorithm)\n    return 0\n\ndef main():\n    input_data = sys.stdin.read().split()\n    if not input_data:\n        return\n    n = int(input_data[0])\n    nums = [int(x) for x in input_data[1:n+1]]\n\n    result = max_sub_array(nums)\n    print(result)\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.Scanner;\n\npublic class Solution {\n    public static int maxSubArray(int[] nums) {\n        // TODO: Implement your solution here (Kadane's algorithm)\n        return 0;\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int n = sc.nextInt();\n        int[] nums = new int[n];\n        for (int i = 0; i < n; i++) nums[i] = sc.nextInt();\n\n        int result = maxSubArray(nums);\n        System.out.println(result);\n    }\n}",
    "cpp": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint maxSubArray(vector<int>& nums) {\n    // TODO: Implement your solution here (Kadane's algorithm)\n    return 0;\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    int n;\n    if (!(cin >> n)) return 0;\n    vector<int> nums(n);\n    for (int i = 0; i < n; i++) cin >> nums[i];\n\n    int result = maxSubArray(nums);\n    cout << result << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint maxSubArray(int* nums, int n) {\n    // TODO: Implement your solution here\n    return 0;\n}\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1) return 0;\n    int* nums = (int*)malloc(n * sizeof(int));\n    for (int i = 0; i < n; i++) scanf(\"%d\", &nums[i]);\n\n    int result = maxSubArray(nums, n);\n    printf(\"%d\\n\", result);\n    free(nums);\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction maxSubArray(nums) {\n    // TODO: Implement your solution here (Kadane's algorithm)\n    return 0;\n}\n\nfunction main() {\n    const input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\n    if (!input || input.length === 0 || isNaN(input[0])) return;\n    const n = input[0];\n    const nums = input.slice(1, n + 1);\n\n    const result = maxSubArray(nums);\n    console.log(result);\n}\n\nmain();"
  },
  "Merge Intervals": {
    "python": "import sys\n\ndef merge_intervals(intervals: list[list[int]]) -> list[list[int]]:\n    # TODO: Implement your solution here\n    return []\n\ndef main():\n    input_data = sys.stdin.read().split()\n    if not input_data:\n        return\n    n = int(input_data[0])\n    intervals = []\n    idx = 1\n    for _ in range(n):\n        intervals.append([int(input_data[idx]), int(input_data[idx+1])])\n        idx += 2\n\n    result = merge_intervals(intervals)\n    for interval in result:\n        print(f\"{interval[0]} {interval[1]}\")\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.*;\n\npublic class Solution {\n    public static List<int[]> merge(int[][] intervals) {\n        // TODO: Implement your solution here\n        return new ArrayList<>();\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int n = sc.nextInt();\n        int[][] intervals = new int[n][2];\n        for (int i = 0; i < n; i++) {\n            intervals[i][0] = sc.nextInt();\n            intervals[i][1] = sc.nextInt();\n        }\n\n        List<int[]> result = merge(intervals);\n        for (int[] interval : result) {\n            System.out.println(interval[0] + \" \" + interval[1]);\n        }\n    }\n}",
    "cpp": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nvector<vector<int>> merge(vector<vector<int>>& intervals) {\n    // TODO: Implement your solution here\n    return {};\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    int n;\n    if (!(cin >> n)) return 0;\n    vector<vector<int>> intervals(n, vector<int>(2));\n    for (int i = 0; i < n; i++) cin >> intervals[i][0] >> intervals[i][1];\n\n    vector<vector<int>> result = merge(intervals);\n    for (const auto& interval : result) {\n        cout << interval[0] << \" \" << interval[1] << \"\\n\";\n    }\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    // TODO: Implement merge intervals\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction merge(intervals) {\n    // TODO: Implement your solution here\n    return [];\n}\n\nfunction main() {\n    const input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\n    if (!input || input.length === 0 || isNaN(input[0])) return;\n    const n = input[0];\n    const intervals = [];\n    let idx = 1;\n    for (let i = 0; i < n; i++) {\n        intervals.push([input[idx], input[idx + 1]]);\n        idx += 2;\n    }\n\n    const result = merge(intervals);\n    for (const interval of result) {\n        console.log(`${interval[0]} ${interval[1]}`);\n    }\n}\n\nmain();"
  },
  "Climbing Stairs": {
    "python": "import sys\n\ndef climb_stairs(n: int) -> int:\n    # TODO: Implement your solution here\n    return 0\n\ndef main():\n    input_data = sys.stdin.read().split()\n    if not input_data:\n        return\n    n = int(input_data[0])\n    result = climb_stairs(n)\n    print(result)\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.Scanner;\n\npublic class Solution {\n    public static int climbStairs(int n) {\n        // TODO: Implement your solution here\n        return 0;\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int n = sc.nextInt();\n        int result = climbStairs(n);\n        System.out.println(result);\n    }\n}",
    "cpp": "#include <iostream>\nusing namespace std;\n\nint climbStairs(int n) {\n    // TODO: Implement your solution here\n    return 0;\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    int n;\n    if (!(cin >> n)) return 0;\n    int result = climbStairs(n);\n    cout << result << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n\nint climbStairs(int n) {\n    // TODO: Implement your solution here\n    return 0;\n}\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1) return 0;\n    int result = climbStairs(n);\n    printf(\"%d\\n\", result);\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction climbStairs(n) {\n    // TODO: Implement your solution here\n    return 0;\n}\n\nfunction main() {\n    const input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\n    if (!input || input.length === 0 || isNaN(input[0])) return;\n    const n = input[0];\n    const result = climbStairs(n);\n    console.log(result);\n}\n\nmain();"
  },
  "Reverse Linked List": {
    "python": "import sys\n\ndef reverse_list(values: list[int]) -> list[int]:\n    # TODO: Implement your solution here\n    return []\n\ndef main():\n    s = sys.stdin.read().strip()\n    if not s:\n        return\n    values = [int(x) for x in s.split()]\n    result = reverse_list(values)\n    print(\" \".join(map(str, result)))\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.*;\n\npublic class Solution {\n    public static List<Integer> reverseList(List<Integer> values) {\n        // TODO: Implement your solution here\n        return new ArrayList<>();\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        List<Integer> values = new ArrayList<>();\n        while (sc.hasNextInt()) {\n            values.add(sc.nextInt());\n        }\n        if (values.isEmpty()) return;\n\n        List<Integer> result = reverseList(values);\n        StringBuilder sb = new StringBuilder();\n        for (int i = 0; i < result.size(); i++) {\n            if (i > 0) sb.append(\" \");\n            sb.append(result.get(i));\n        }\n        System.out.println(sb.toString());\n    }\n}",
    "cpp": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nvector<int> reverseList(const vector<int>& values) {\n    // TODO: Implement your solution here\n    return {};\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    vector<int> values;\n    int val;\n    while (cin >> val) values.push_back(val);\n    if (values.empty()) return 0;\n\n    vector<int> result = reverseList(values);\n    for (size_t i = 0; i < result.size(); i++) {\n        cout << result[i] << (i + 1 == result.size() ? \"\" : \" \");\n    }\n    cout << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    // TODO: Implement reverse linked list\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction reverseList(values) {\n    // TODO: Implement your solution here\n    return [];\n}\n\nfunction main() {\n    const input = fs.readFileSync(0, 'utf-8').trim();\n    if (!input) return;\n    const values = input.split(/\\s+/).map(Number);\n    const result = reverseList(values);\n    console.log(result.join(' '));\n}\n\nmain();"
  },
  "Contains Duplicate": {
    "python": "import sys\n\ndef contains_duplicate(nums: list[int]) -> bool:\n    # TODO: Implement your solution here\n    return False\n\ndef main():\n    input_data = sys.stdin.read().split()\n    if not input_data:\n        return\n    n = int(input_data[0])\n    nums = [int(x) for x in input_data[1:n+1]]\n\n    result = contains_duplicate(nums)\n    print(\"true\" if result else \"false\")\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.*;\n\npublic class Solution {\n    public static boolean containsDuplicate(int[] nums) {\n        // TODO: Implement your solution here\n        return false;\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int n = sc.nextInt();\n        int[] nums = new int[n];\n        for (int i = 0; i < n; i++) nums[i] = sc.nextInt();\n\n        boolean result = containsDuplicate(nums);\n        System.out.println(result ? \"true\" : \"false\");\n    }\n}",
    "cpp": "#include <iostream>\n#include <vector>\n#include <unordered_set>\nusing namespace std;\n\nbool containsDuplicate(vector<int>& nums) {\n    // TODO: Implement your solution here\n    return false;\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    int n;\n    if (!(cin >> n)) return 0;\n    vector<int> nums(n);\n    for (int i = 0; i < n; i++) cin >> nums[i];\n\n    bool result = containsDuplicate(nums);\n    cout << (result ? \"true\" : \"false\") << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n#include <stdbool.h>\n\nbool containsDuplicate(int* nums, int n) {\n    // TODO: Implement your solution here\n    return false;\n}\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1) return 0;\n    int* nums = (int*)malloc(n * sizeof(int));\n    for (int i = 0; i < n; i++) scanf(\"%d\", &nums[i]);\n\n    bool result = containsDuplicate(nums, n);\n    printf(\"%s\\n\", result ? \"true\" : \"false\");\n    free(nums);\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction containsDuplicate(nums) {\n    // TODO: Implement your solution here\n    return false;\n}\n\nfunction main() {\n    const input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\n    if (!input || input.length === 0 || isNaN(input[0])) return;\n    const n = input[0];\n    const nums = input.slice(1, n + 1);\n\n    const result = containsDuplicate(nums);\n    console.log(result ? \"true\" : \"false\");\n}\n\nmain();"
  },
  "Product of Array Except Self": {
    "python": "import sys\n\ndef product_except_self(nums: list[int]) -> list[int]:\n    # TODO: Implement your solution here (O(n) time, without division)\n    return []\n\ndef main():\n    input_data = sys.stdin.read().split()\n    if not input_data:\n        return\n    n = int(input_data[0])\n    nums = [int(x) for x in input_data[1:n+1]]\n\n    result = product_except_self(nums)\n    print(\" \".join(map(str, result)))\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.Scanner;\n\npublic class Solution {\n    public static int[] productExceptSelf(int[] nums) {\n        // TODO: Implement your solution here (O(n) time, without division)\n        return new int[]{};\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int n = sc.nextInt();\n        int[] nums = new int[n];\n        for (int i = 0; i < n; i++) nums[i] = sc.nextInt();\n\n        int[] result = productExceptSelf(nums);\n        StringBuilder sb = new StringBuilder();\n        for (int i = 0; i < result.length; i++) {\n            if (i > 0) sb.append(\" \");\n            sb.append(result[i]);\n        }\n        System.out.println(sb.toString());\n    }\n}",
    "cpp": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nvector<int> productExceptSelf(vector<int>& nums) {\n    // TODO: Implement your solution here (O(n) time, without division)\n    return {};\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    int n;\n    if (!(cin >> n)) return 0;\n    vector<int> nums(n);\n    for (int i = 0; i < n; i++) cin >> nums[i];\n\n    vector<int> result = productExceptSelf(nums);\n    for (size_t i = 0; i < result.size(); i++) {\n        cout << result[i] << (i + 1 == result.size() ? \"\" : \" \");\n    }\n    cout << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    // TODO: Implement product of array except self\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction productExceptSelf(nums) {\n    // TODO: Implement your solution here (O(n) time, without division)\n    return [];\n}\n\nfunction main() {\n    const input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\n    if (!input || input.length === 0 || isNaN(input[0])) return;\n    const n = input[0];\n    const nums = input.slice(1, n + 1);\n\n    const result = productExceptSelf(nums);\n    console.log(result.join(' '));\n}\n\nmain();"
  },
  "Valid Anagram": {
    "python": "import sys\n\ndef is_anagram(s: str, t: str) -> bool:\n    # TODO: Implement your solution here\n    return False\n\ndef main():\n    lines = sys.stdin.read().splitlines()\n    if len(lines) < 2:\n        return\n    s = lines[0].strip()\n    t = lines[1].strip()\n\n    result = is_anagram(s, t)\n    print(\"true\" if result else \"false\")\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.Scanner;\n\npublic class Solution {\n    public static boolean isAnagram(String s, String t) {\n        // TODO: Implement your solution here\n        return false;\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.hasNextLine() ? sc.nextLine().trim() : \"\";\n        String t = sc.hasNextLine() ? sc.nextLine().trim() : \"\";\n\n        boolean result = isAnagram(s, t);\n        System.out.println(result ? \"true\" : \"false\");\n    }\n}",
    "cpp": "#include <iostream>\n#include <string>\nusing namespace std;\n\nbool isAnagram(const string& s, const string& t) {\n    // TODO: Implement your solution here\n    return false;\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    string s, t;\n    if (!(cin >> s >> t)) return 0;\n\n    bool result = isAnagram(s, t);\n    cout << (result ? \"true\" : \"false\") << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <string.h>\n#include <stdbool.h>\n\nbool isAnagram(const char* s, const char* t) {\n    // TODO: Implement your solution here\n    return false;\n}\n\nint main() {\n    char s[100005], t[100005];\n    if (scanf(\"%100000s %100000s\", s, t) != 2) return 0;\n    bool result = isAnagram(s, t);\n    printf(\"%s\\n\", result ? \"true\" : \"false\");\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction isAnagram(s, t) {\n    // TODO: Implement your solution here\n    return false;\n}\n\nfunction main() {\n    const input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/);\n    if (!input || input.length < 2) return;\n    const s = input[0];\n    const t = input[1];\n\n    const result = isAnagram(s, t);\n    console.log(result ? \"true\" : \"false\");\n}\n\nmain();"
  },
  "Group Anagrams": {
    "python": "import sys\n\ndef group_anagrams(strs: list[str]) -> list[list[str]]:\n    # TODO: Implement your solution here\n    return []\n\ndef main():\n    words = sys.stdin.read().split()\n    if not words:\n        return\n\n    result = group_anagrams(words)\n    # Print sorted groups for deterministic testing\n    for group in result:\n        print(\" \".join(group))\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.*;\n\npublic class Solution {\n    public static List<List<String>> groupAnagrams(String[] strs) {\n        // TODO: Implement your solution here\n        return new ArrayList<>();\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        List<String> words = new ArrayList<>();\n        while (sc.hasNext()) {\n            words.add(sc.next());\n        }\n        if (words.isEmpty()) return;\n\n        List<List<String>> result = groupAnagrams(words.toArray(new String[0]));\n        for (List<String> group : result) {\n            System.out.println(String.join(\" \", group));\n        }\n    }\n}",
    "cpp": "#include <iostream>\n#include <vector>\n#include <string>\n#include <unordered_map>\nusing namespace std;\n\nvector<vector<string>> groupAnagrams(vector<string>& strs) {\n    // TODO: Implement your solution here\n    return {};\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    vector<string> words;\n    string word;\n    while (cin >> word) words.push_back(word);\n    if (words.empty()) return 0;\n\n    vector<vector<string>> result = groupAnagrams(words);\n    for (const auto& group : result) {\n        for (size_t i = 0; i < group.size(); i++) {\n            cout << group[i] << (i + 1 == group.size() ? \"\" : \" \");\n        }\n        cout << \"\\n\";\n    }\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    // TODO: Implement group anagrams\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction groupAnagrams(strs) {\n    // TODO: Implement your solution here\n    return [];\n}\n\nfunction main() {\n    const words = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/);\n    if (!words || words.length === 0 || !words[0]) return;\n\n    const result = groupAnagrams(words);\n    for (const group of result) {\n        console.log(group.join(' '));\n    }\n}\n\nmain();"
  },
  "Binary Search": {
    "python": "import sys\n\ndef search(nums: list[int], target: int) -> int:\n    # TODO: Implement your solution here (O(log n))\n    return -1\n\ndef main():\n    input_data = sys.stdin.read().split()\n    if not input_data:\n        return\n    n = int(input_data[0])\n    nums = [int(x) for x in input_data[1:n+1]]\n    target = int(input_data[n+1])\n\n    result = search(nums, target)\n    print(result)\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.Scanner;\n\npublic class Solution {\n    public static int search(int[] nums, int target) {\n        // TODO: Implement your solution here (O(log n))\n        return -1;\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int n = sc.nextInt();\n        int[] nums = new int[n];\n        for (int i = 0; i < n; i++) nums[i] = sc.nextInt();\n        int target = sc.nextInt();\n\n        int result = search(nums, target);\n        System.out.println(result);\n    }\n}",
    "cpp": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint search(vector<int>& nums, int target) {\n    // TODO: Implement your solution here (O(log n))\n    return -1;\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    int n;\n    if (!(cin >> n)) return 0;\n    vector<int> nums(n);\n    for (int i = 0; i < n; i++) cin >> nums[i];\n    int target;\n    cin >> target;\n\n    int result = search(nums, target);\n    cout << result << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint search(int* nums, int n, int target) {\n    // TODO: Implement your solution here\n    return -1;\n}\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1) return 0;\n    int* nums = (int*)malloc(n * sizeof(int));\n    for (int i = 0; i < n; i++) scanf(\"%d\", &nums[i]);\n    int target;\n    scanf(\"%d\", &target);\n\n    int result = search(nums, n, target);\n    printf(\"%d\\n\", result);\n    free(nums);\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction search(nums, target) {\n    // TODO: Implement your solution here (O(log n))\n    return -1;\n}\n\nfunction main() {\n    const input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\n    if (!input || input.length === 0 || isNaN(input[0])) return;\n    const n = input[0];\n    const nums = input.slice(1, n + 1);\n    const target = input[n + 1];\n\n    const result = search(nums, target);\n    console.log(result);\n}\n\nmain();"
  },
  "Search in Rotated Sorted Array": {
    "python": "import sys\n\ndef search(nums: list[int], target: int) -> int:\n    # TODO: Implement your solution here (O(log n))\n    return -1\n\ndef main():\n    input_data = sys.stdin.read().split()\n    if not input_data:\n        return\n    n = int(input_data[0])\n    nums = [int(x) for x in input_data[1:n+1]]\n    target = int(input_data[n+1])\n\n    result = search(nums, target)\n    print(result)\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.Scanner;\n\npublic class Solution {\n    public static int search(int[] nums, int target) {\n        // TODO: Implement your solution here (O(log n))\n        return -1;\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int n = sc.nextInt();\n        int[] nums = new int[n];\n        for (int i = 0; i < n; i++) nums[i] = sc.nextInt();\n        int target = sc.nextInt();\n\n        int result = search(nums, target);\n        System.out.println(result);\n    }\n}",
    "cpp": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint search(vector<int>& nums, int target) {\n    // TODO: Implement your solution here (O(log n))\n    return -1;\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    int n;\n    if (!(cin >> n)) return 0;\n    vector<int> nums(n);\n    for (int i = 0; i < n; i++) cin >> nums[i];\n    int target;\n    cin >> target;\n\n    int result = search(nums, target);\n    cout << result << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint search(int* nums, int n, int target) {\n    // TODO: Implement your solution here\n    return -1;\n}\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1) return 0;\n    int* nums = (int*)malloc(n * sizeof(int));\n    for (int i = 0; i < n; i++) scanf(\"%d\", &nums[i]);\n    int target;\n    scanf(\"%d\", &target);\n\n    int result = search(nums, n, target);\n    printf(\"%d\\n\", result);\n    free(nums);\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction search(nums, target) {\n    // TODO: Implement your solution here (O(log n))\n    return -1;\n}\n\nfunction main() {\n    const input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\n    if (!input || input.length === 0 || isNaN(input[0])) return;\n    const n = input[0];\n    const nums = input.slice(1, n + 1);\n    const target = input[n + 1];\n\n    const result = search(nums, target);\n    console.log(result);\n}\n\nmain();"
  },
  "Daily Temperatures": {
    "python": "import sys\n\ndef daily_temperatures(temperatures: list[int]) -> list[int]:\n    # TODO: Implement your solution here (monotonic stack)\n    return []\n\ndef main():\n    input_data = sys.stdin.read().split()\n    if not input_data:\n        return\n    n = int(input_data[0])\n    temperatures = [int(x) for x in input_data[1:n+1]]\n\n    result = daily_temperatures(temperatures)\n    print(\" \".join(map(str, result)))\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.*;\n\npublic class Solution {\n    public static int[] dailyTemperatures(int[] temperatures) {\n        // TODO: Implement your solution here (monotonic stack)\n        return new int[]{};\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int n = sc.nextInt();\n        int[] temperatures = new int[n];\n        for (int i = 0; i < n; i++) temperatures[i] = sc.nextInt();\n\n        int[] result = dailyTemperatures(temperatures);\n        StringBuilder sb = new StringBuilder();\n        for (int i = 0; i < result.length; i++) {\n            if (i > 0) sb.append(\" \");\n            sb.append(result[i]);\n        }\n        System.out.println(sb.toString());\n    }\n}",
    "cpp": "#include <iostream>\n#include <vector>\n#include <stack>\nusing namespace std;\n\nvector<int> dailyTemperatures(vector<int>& temperatures) {\n    // TODO: Implement your solution here (monotonic stack)\n    return {};\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    int n;\n    if (!(cin >> n)) return 0;\n    vector<int> temperatures(n);\n    for (int i = 0; i < n; i++) cin >> temperatures[i];\n\n    vector<int> result = dailyTemperatures(temperatures);\n    for (size_t i = 0; i < result.size(); i++) {\n        cout << result[i] << (i + 1 == result.size() ? \"\" : \" \");\n    }\n    cout << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    // TODO: Implement daily temperatures\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction dailyTemperatures(temperatures) {\n    // TODO: Implement your solution here (monotonic stack)\n    return [];\n}\n\nfunction main() {\n    const input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\n    if (!input || input.length === 0 || isNaN(input[0])) return;\n    const n = input[0];\n    const temperatures = input.slice(1, n + 1);\n\n    const result = dailyTemperatures(temperatures);\n    console.log(result.join(' '));\n}\n\nmain();"
  },
  "House Robber": {
    "python": "import sys\n\ndef rob(nums: list[int]) -> int:\n    # TODO: Implement your solution here (dynamic programming)\n    return 0\n\ndef main():\n    input_data = sys.stdin.read().split()\n    if not input_data:\n        return\n    n = int(input_data[0])\n    nums = [int(x) for x in input_data[1:n+1]]\n\n    result = rob(nums)\n    print(result)\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.Scanner;\n\npublic class Solution {\n    public static int rob(int[] nums) {\n        // TODO: Implement your solution here (dynamic programming)\n        return 0;\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int n = sc.nextInt();\n        int[] nums = new int[n];\n        for (int i = 0; i < n; i++) nums[i] = sc.nextInt();\n\n        int result = rob(nums);\n        System.out.println(result);\n    }\n}",
    "cpp": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint rob(vector<int>& nums) {\n    // TODO: Implement your solution here (dynamic programming)\n    return 0;\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    int n;\n    if (!(cin >> n)) return 0;\n    vector<int> nums(n);\n    for (int i = 0; i < n; i++) cin >> nums[i];\n\n    int result = rob(nums);\n    cout << result << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint rob(int* nums, int n) {\n    // TODO: Implement your solution here\n    return 0;\n}\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1) return 0;\n    int* nums = (int*)malloc(n * sizeof(int));\n    for (int i = 0; i < n; i++) scanf(\"%d\", &nums[i]);\n\n    int result = rob(nums, n);\n    printf(\"%d\\n\", result);\n    free(nums);\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction rob(nums) {\n    // TODO: Implement your solution here (dynamic programming)\n    return 0;\n}\n\nfunction main() {\n    const input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\n    if (!input || input.length === 0 || isNaN(input[0])) return;\n    const n = input[0];\n    const nums = input.slice(1, n + 1);\n\n    const result = rob(nums);\n    console.log(result);\n}\n\nmain();"
  },
  "Coin Change": {
    "python": "import sys\n\ndef coin_change(coins: list[int], amount: int) -> int:\n    # TODO: Implement your solution here (fewest coins to make up amount, or -1)\n    return -1\n\ndef main():\n    input_data = sys.stdin.read().split()\n    if not input_data:\n        return\n    n = int(input_data[0])\n    coins = [int(x) for x in input_data[1:n+1]]\n    amount = int(input_data[n+1])\n\n    result = coin_change(coins, amount)\n    print(result)\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.Scanner;\n\npublic class Solution {\n    public static int coinChange(int[] coins, int amount) {\n        // TODO: Implement your solution here (fewest coins to make up amount, or -1)\n        return -1;\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int n = sc.nextInt();\n        int[] coins = new int[n];\n        for (int i = 0; i < n; i++) coins[i] = sc.nextInt();\n        int amount = sc.nextInt();\n\n        int result = coinChange(coins, amount);\n        System.out.println(result);\n    }\n}",
    "cpp": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint coinChange(vector<int>& coins, int amount) {\n    // TODO: Implement your solution here (fewest coins to make up amount, or -1)\n    return -1;\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    int n;\n    if (!(cin >> n)) return 0;\n    vector<int> coins(n);\n    for (int i = 0; i < n; i++) cin >> coins[i];\n    int amount;\n    cin >> amount;\n\n    int result = coinChange(coins, amount);\n    cout << result << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint coinChange(int* coins, int n, int amount) {\n    // TODO: Implement your solution here\n    return -1;\n}\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1) return 0;\n    int* coins = (int*)malloc(n * sizeof(int));\n    for (int i = 0; i < n; i++) scanf(\"%d\", &coins[i]);\n    int amount;\n    scanf(\"%d\", &amount);\n\n    int result = coinChange(coins, n, amount);\n    printf(\"%d\\n\", result);\n    free(coins);\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction coinChange(coins, amount) {\n    // TODO: Implement your solution here (fewest coins to make up amount, or -1)\n    return -1;\n}\n\nfunction main() {\n    const input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\n    if (!input || input.length === 0 || isNaN(input[0])) return;\n    const n = input[0];\n    const coins = input.slice(1, n + 1);\n    const amount = input[n + 1];\n\n    const result = coinChange(coins, amount);\n    console.log(result);\n}\n\nmain();"
  },
  "Number of Islands": {
    "python": "import sys\n\ndef num_islands(grid: list[list[str]]) -> int:\n    # TODO: Implement your solution here (grid traversal: DFS / BFS)\n    return 0\n\ndef main():\n    lines = sys.stdin.read().strip().split('\\n')\n    if not lines or not lines[0].strip():\n        return\n    first = lines[0].split()\n    m, n = int(first[0]), int(first[1])\n    grid = []\n    for i in range(1, m + 1):\n        if i < len(lines):\n            grid.append(list(lines[i].strip()))\n\n    result = num_islands(grid)\n    print(result)\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.Scanner;\n\npublic class Solution {\n    public static int numIslands(char[][] grid) {\n        // TODO: Implement your solution here (grid traversal: DFS / BFS)\n        return 0;\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int m = sc.nextInt();\n        int n = sc.nextInt();\n        char[][] grid = new char[m][n];\n        for (int i = 0; i < m; i++) {\n            String row = sc.next();\n            for (int j = 0; j < n && j < row.length(); j++) {\n                grid[i][j] = row.charAt(j);\n            }\n        }\n\n        int result = numIslands(grid);\n        System.out.println(result);\n    }\n}",
    "cpp": "#include <iostream>\n#include <vector>\n#include <string>\nusing namespace std;\n\nint numIslands(vector<vector<char>>& grid) {\n    // TODO: Implement your solution here (grid traversal: DFS / BFS)\n    return 0;\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    int m, n;\n    if (!(cin >> m >> n)) return 0;\n    vector<vector<char>> grid(m, vector<char>(n));\n    for (int i = 0; i < m; i++) {\n        string row;\n        cin >> row;\n        for (int j = 0; j < n && j < (int)row.size(); j++) {\n            grid[i][j] = row[j];\n        }\n    }\n\n    int result = numIslands(grid);\n    cout << result << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    // TODO: Implement number of islands\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction numIslands(grid) {\n    // TODO: Implement your solution here (grid traversal: DFS / BFS)\n    return 0;\n}\n\nfunction main() {\n    const lines = fs.readFileSync(0, 'utf-8').trim().split('\\n');\n    if (!lines || lines.length === 0 || !lines[0].trim()) return;\n    const [m, n] = lines[0].trim().split(/\\s+/).map(Number);\n    const grid = [];\n    for (let i = 1; i <= m && i < lines.length; i++) {\n        grid.push(lines[i].trim().split(''));\n    }\n\n    const result = numIslands(grid);\n    console.log(result);\n}\n\nmain();"
  },
  "Trapping Rain Water": {
    "python": "import sys\n\ndef trap(height: list[int]) -> int:\n    # TODO: Implement your solution here (two-pointer or prefix/suffix maximums)\n    return 0\n\ndef main():\n    input_data = sys.stdin.read().split()\n    if not input_data:\n        return\n    n = int(input_data[0])\n    height = [int(x) for x in input_data[1:n+1]]\n\n    result = trap(height)\n    print(result)\n\nif __name__ == \"__main__\":\n    main()",
    "java": "import java.util.Scanner;\n\npublic class Solution {\n    public static int trap(int[] height) {\n        // TODO: Implement your solution here (two-pointer or prefix/suffix maximums)\n        return 0;\n    }\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int n = sc.nextInt();\n        int[] height = new int[n];\n        for (int i = 0; i < n; i++) height[i] = sc.nextInt();\n\n        int result = trap(height);\n        System.out.println(result);\n    }\n}",
    "cpp": "#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint trap(vector<int>& height) {\n    // TODO: Implement your solution here (two-pointer or prefix/suffix maximums)\n    return 0;\n}\n\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    int n;\n    if (!(cin >> n)) return 0;\n    vector<int> height(n);\n    for (int i = 0; i < n; i++) cin >> height[i];\n\n    int result = trap(height);\n    cout << result << \"\\n\";\n    return 0;\n}",
    "c": "#include <stdio.h>\n#include <stdlib.h>\n\nint trap(int* height, int n) {\n    // TODO: Implement your solution here\n    return 0;\n}\n\nint main() {\n    int n;\n    if (scanf(\"%d\", &n) != 1) return 0;\n    int* height = (int*)malloc(n * sizeof(int));\n    for (int i = 0; i < n; i++) scanf(\"%d\", &height[i]);\n\n    int result = trap(height, n);\n    printf(\"%d\\n\", result);\n    free(height);\n    return 0;\n}",
    "javascript": "const fs = require('fs');\n\nfunction trap(height) {\n    // TODO: Implement your solution here (two-pointer or prefix/suffix maximums)\n    return 0;\n}\n\nfunction main() {\n    const input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/).map(Number);\n    if (!input || input.length === 0 || isNaN(input[0])) return;\n    const n = input[0];\n    const height = input.slice(1, n + 1);\n\n    const result = trap(height);\n    console.log(result);\n}\n\nmain();"
  },
  "Combine Two Tables": {
    "mysql": "# Write your MySQL query statement below\nSELECT \n    p.firstName, p.lastName, a.city, a.state\nFROM \n    Person p\nLEFT JOIN \n    Address a ON p.personId = a.personId;\n",
    "sql": "-- Write your SQL query statement below\nSELECT \n    p.firstName, p.lastName, a.city, a.state\nFROM \n    Person p\nLEFT JOIN \n    Address a ON p.personId = a.personId;\n"
  },
  "Employees Earning More Than Their Managers": {
    "mysql": "# Write your MySQL query statement below\nSELECT \n    e.name AS Employee\nFROM \n    Employee e\nJOIN \n    Employee m ON e.managerId = m.id\nWHERE \n    e.salary > m.salary;\n",
    "sql": "-- Write your SQL query statement below\nSELECT \n    e.name AS Employee\nFROM \n    Employee e\nJOIN \n    Employee m ON e.managerId = m.id\nWHERE \n    e.salary > m.salary;\n"
  },
  "Duplicate Emails": {
    "mysql": "# Write your MySQL query statement below\nSELECT \n    email AS Email\nFROM \n    Person\nGROUP BY \n    email\nHAVING \n    COUNT(email) > 1;\n",
    "sql": "-- Write your SQL query statement below\nSELECT \n    email AS Email\nFROM \n    Person\nGROUP BY \n    email\nHAVING \n    COUNT(email) > 1;\n"
  },
  "Customers Who Never Order": {
    "mysql": "# Write your MySQL query statement below\nSELECT \n    c.name AS Customers\nFROM \n    Customers c\nLEFT JOIN \n    Orders o ON c.id = o.customerId\nWHERE \n    o.id IS NULL;\n",
    "sql": "-- Write your SQL query statement below\nSELECT \n    c.name AS Customers\nFROM \n    Customers c\nLEFT JOIN \n    Orders o ON c.id = o.customerId\nWHERE \n    o.id IS NULL;\n"
  },
  "Second Highest Salary": {
    "mysql": "# Write your MySQL query statement below\nSELECT (\n    SELECT DISTINCT salary\n    FROM Employee\n    ORDER BY salary DESC\n    LIMIT 1 OFFSET 1\n) AS SecondHighestSalary;\n",
    "sql": "-- Write your SQL query statement below\nSELECT (\n    SELECT DISTINCT salary\n    FROM Employee\n    ORDER BY salary DESC\n    LIMIT 1 OFFSET 1\n) AS SecondHighestSalary;\n"
  },
  "Department Highest Salary": {
    "mysql": "# Write your MySQL query statement below\nSELECT \n    d.name AS Department,\n    e.name AS Employee,\n    e.salary AS Salary\nFROM \n    Employee e\nJOIN \n    Department d ON e.departmentId = d.id\nWHERE \n    (e.departmentId, e.salary) IN (\n        SELECT departmentId, MAX(salary)\n        FROM Employee\n        GROUP BY departmentId\n    );\n",
    "sql": "-- Write your SQL query statement below\nSELECT \n    d.name AS Department,\n    e.name AS Employee,\n    e.salary AS Salary\nFROM \n    Employee e\nJOIN \n    Department d ON e.departmentId = d.id\nWHERE \n    (e.departmentId, e.salary) IN (\n        SELECT departmentId, MAX(salary)\n        FROM Employee\n        GROUP BY departmentId\n    );\n"
  },
  "Rank Scores": {
    "mysql": "# Write your MySQL query statement below\nSELECT \n    score,\n    DENSE_RANK() OVER (ORDER BY score DESC) AS `rank`\nFROM \n    Scores;\n",
    "sql": "-- Write your SQL query statement below\nSELECT \n    score,\n    DENSE_RANK() OVER (ORDER BY score DESC) AS rank\nFROM \n    Scores;\n"
  },
  "Consecutive Numbers": {
    "mysql": "# Write your MySQL query statement below\nSELECT DISTINCT\n    l1.num AS ConsecutiveNums\nFROM\n    Logs l1,\n    Logs l2,\n    Logs l3\nWHERE\n    l1.id = l2.id - 1\n    AND l2.id = l3.id - 1\n    AND l1.num = l2.num\n    AND l2.num = l3.num;\n",
    "sql": "-- Write your SQL query statement below\nSELECT DISTINCT\n    l1.num AS ConsecutiveNums\nFROM\n    Logs l1\nJOIN Logs l2 ON l1.id = l2.id - 1 AND l1.num = l2.num\nJOIN Logs l3 ON l2.id = l3.id - 1 AND l2.num = l3.num;\n"
  },
  "Department Top Three Salaries": {
    "mysql": "# Write your MySQL query statement below\nWITH Ranked AS (\n    SELECT \n        d.name AS Department,\n        e.name AS Employee,\n        e.salary AS Salary,\n        DENSE_RANK() OVER (PARTITION BY e.departmentId ORDER BY e.salary DESC) AS rnk\n    FROM Employee e\n    JOIN Department d ON e.departmentId = d.id\n)\nSELECT Department, Employee, Salary\nFROM Ranked\nWHERE rnk <= 3;\n",
    "sql": "-- Write your SQL query statement below\nWITH Ranked AS (\n    SELECT \n        d.name AS Department,\n        e.name AS Employee,\n        e.salary AS Salary,\n        DENSE_RANK() OVER (PARTITION BY e.departmentId ORDER BY e.salary DESC) AS rnk\n    FROM Employee e\n    JOIN Department d ON e.departmentId = d.id\n)\nSELECT Department, Employee, Salary\nFROM Ranked\nWHERE rnk <= 3;\n"
  },
  "Delete Duplicate Emails": {
    "mysql": "# Write your MySQL query statement below\nDELETE p1 FROM Person p1\nJOIN Person p2 ON p1.email = p2.email AND p1.id > p2.id;\n",
    "sql": "-- Write your SQL query statement below\nDELETE FROM Person\nWHERE id NOT IN (\n    SELECT MIN(id) FROM (\n        SELECT * FROM Person\n    ) AS temp\n    GROUP BY email\n);\n"
  },
  "Rising Temperature": {
    "mysql": "# Write your MySQL query statement below\nSELECT w1.id\nFROM Weather w1\nJOIN Weather w2 ON w1.recordDate = DATE_ADD(w2.recordDate, INTERVAL 1 DAY)\nWHERE w1.temperature > w2.temperature;\n",
    "sql": "-- Write your SQL query statement below\nSELECT w1.id\nFROM Weather w1\nJOIN Weather w2 ON julianday(w1.recordDate) = julianday(w2.recordDate) + 1\nWHERE w1.temperature > w2.temperature;\n"
  },
  "Trips and Users": {
    "mysql": "# Write your MySQL query statement below\nSELECT \n    t.request_at AS Day,\n    ROUND(\n        SUM(IF(t.status != 'completed', 1, 0)) / COUNT(*),\n        2\n    ) AS `Cancellation Rate`\nFROM Trips t\nJOIN Users c ON t.client_id = c.users_id AND c.banned = 'No'\nJOIN Users d ON t.driver_id = d.users_id AND d.banned = 'No'\nWHERE t.request_at BETWEEN '2013-10-01' AND '2013-10-03'\nGROUP BY t.request_at;\n",
    "sql": "-- Write your SQL query statement below\nSELECT \n    t.request_at AS Day,\n    ROUND(\n        CAST(SUM(CASE WHEN t.status != 'completed' THEN 1 ELSE 0 END) AS REAL) / COUNT(*),\n        2\n    ) AS \"Cancellation Rate\"\nFROM Trips t\nJOIN Users c ON t.client_id = c.users_id AND c.banned = 'No'\nJOIN Users d ON t.driver_id = d.users_id AND d.banned = 'No'\nWHERE t.request_at BETWEEN '2013-10-01' AND '2013-10-03'\nGROUP BY t.request_at;\n"
  },
  "Market Analysis I": {
    "mysql": "# Write your MySQL query statement below\nSELECT \n    u.user_id AS buyer_id,\n    u.join_date,\n    COUNT(o.order_id) AS orders_in_2019\nFROM Users u\nLEFT JOIN Orders o ON u.user_id = o.buyer_id AND o.order_date LIKE '2019%'\nGROUP BY u.user_id, u.join_date;\n",
    "sql": "-- Write your SQL query statement below\nSELECT \n    u.user_id AS buyer_id,\n    u.join_date,\n    COUNT(o.order_id) AS orders_in_2019\nFROM Users u\nLEFT JOIN Orders o ON u.user_id = o.buyer_id AND strftime('%Y', o.order_date) = '2019'\nGROUP BY u.user_id, u.join_date;\n"
  },
  "Investments in 2016": {
    "mysql": "# Write your MySQL query statement below\nSELECT ROUND(SUM(tiv_2016), 2) AS tiv_2016\nFROM Insurance\nWHERE tiv_2015 IN (\n    SELECT tiv_2015\n    FROM Insurance\n    GROUP BY tiv_2015\n    HAVING COUNT(*) > 1\n)\nAND (lat, lon) IN (\n    SELECT lat, lon\n    FROM Insurance\n    GROUP BY lat, lon\n    HAVING COUNT(*) = 1\n);\n",
    "sql": "-- Write your SQL query statement below\nSELECT ROUND(SUM(tiv_2016), 2) AS tiv_2016\nFROM Insurance\nWHERE tiv_2015 IN (\n    SELECT tiv_2015\n    FROM Insurance\n    GROUP BY tiv_2015\n    HAVING COUNT(*) > 1\n)\nAND (lat, lon) IN (\n    SELECT lat, lon\n    FROM Insurance\n    GROUP BY lat, lon\n    HAVING COUNT(*) = 1\n);\n"
  },
  "Tree Node Classification": {
    "mysql": "# Write your MySQL query statement below\nSELECT \n    id,\n    CASE \n        WHEN p_id IS NULL THEN 'Root'\n        WHEN id IN (SELECT DISTINCT p_id FROM Tree WHERE p_id IS NOT NULL) THEN 'Inner'\n        ELSE 'Leaf'\n    END AS type\nFROM Tree;\n",
    "sql": "-- Write your SQL query statement below\nSELECT \n    id,\n    CASE \n        WHEN p_id IS NULL THEN 'Root'\n        WHEN id IN (SELECT DISTINCT p_id FROM Tree WHERE p_id IS NOT NULL) THEN 'Inner'\n        ELSE 'Leaf'\n    END AS type\nFROM Tree;\n"
  }
};

/**
 * Normalizes a problem title or slug to match snippet keys.
 */
function normalizeKey(title) {
  if (!title) return '';
  return title.trim().toLowerCase().replace(/[^a-z0-9]/g, '');
}

// Build slug lookup map for case/punctuation-insensitive lookup
const SLUG_MAP = {};
for (const key of Object.keys(PROBLEM_STARTER_SNIPPETS)) {
  SLUG_MAP[normalizeKey(key)] = key;
}

/**
 * Retrieves the starter code snippet tailored for a specific problem and language.
 *
 * @param {Object|string} problem - The problem object or problem title
 * @param {string} language - The target programming language ('java'|'python'|'cpp'|'c'|'javascript')
 * @returns {string} The compatible starter snippet for the problem and language
 */
export function getStarterSnippet(problem, language = 'java') {
  const langKey = (language || 'java').toLowerCase();
  
  const title = typeof problem === 'string' ? problem : (problem?.title || '');
  if (!title) {
    return DEFAULT_TEMPLATES[langKey] || DEFAULT_TEMPLATES.java;
  }

  // Exact match
  if (PROBLEM_STARTER_SNIPPETS[title] && PROBLEM_STARTER_SNIPPETS[title][langKey]) {
    return PROBLEM_STARTER_SNIPPETS[title][langKey];
  }

  // Normalized slug match
  const slug = normalizeKey(title);
  const matchedKey = SLUG_MAP[slug];
  if (matchedKey && PROBLEM_STARTER_SNIPPETS[matchedKey] && PROBLEM_STARTER_SNIPPETS[matchedKey][langKey]) {
    return PROBLEM_STARTER_SNIPPETS[matchedKey][langKey];
  }

  // Dynamic fallback for custom uploaded problems
  return DEFAULT_TEMPLATES[langKey] || DEFAULT_TEMPLATES.java;
}

export default {
  DEFAULT_TEMPLATES,
  PROBLEM_STARTER_SNIPPETS,
  getStarterSnippet,
};
